def report_header():
    return """
    INTELLIGENT SALES FORECASTING REPORT
    ===================================
    """

def report_footer():
    return """
    ===================================
    Generated by Intelligent Sales System
    """